# app/models/__init__.py
from .accidente_model import Accidente
from .baja_model import Baja
from .cambio_motor_model import CambioMotor
from .chofer_model import Chofer
from .dependencia_model import Dependencia
from .donacion_model import Donacion
from .localidad_model import Localidad
from .novedad_model import Novedad
from .provincia_model import Provincia
from .reparacion_model import Reparacion
from .robo_model import Robo
from .taller_model import Taller
from .tipo_acto_model import TipoActo
from .tipo_carroceria_model import TipoCarroceria
from .tipo_condicion_model import TipoCondicion
from .tipo_documento_model import TipoDocumento
from .tipo_marca_model import TipoMarca
from .tipo_modelo_model import TipoModelo
from .tipo_motor_model import TipoMotor
from .tipo_novedad_model import TipoNovedad
from .tipo_reparacionEstado_model import TipoReparacionEstado
from .tipo_situacion_model import TipoSituacion
from .tipo_situacion_chofer_model import TipoSituacionChofer
from .tipo_aptitud_model import TipoAptitud
from .tipo_cabina_model import TipoCabina
from .tipo_traccion_model import TipoTraccion
from .tipo_vehiculo_model import TipoVehiculo
from .tipo_vtvResultado_model import TipoVtvResultado
from .tipo_pago_model import TipoPago
from .transferencia_model import Transferencia
from .tipo_tramite_dependencia_model import TipoTramiteDependencia
from .vehiculo_dependencia_model import VehiculoDependencia
from .vehiculo_model import Vehiculo
from .vtv_model import Vtv
from .cambio_chasis_model import CambioChasis
from .comodato_model import Comodato
from .infraccion_model import Infraccion
from .role_model import Role
from .user_model import User